### PR TITLE
Allow alternative fs to be specified in options and used for fs interactions

### LINKED ISSUE #20: Allow alternative fs to be used for reading files
Main driver for this is explained: https://github.com/pahen/madge/issues/186

Allow an alternative `fs` to be provided via options, and if provided, use that instead of the default system provided `fs` when looking up amd modules.

Some dependencies may need to adapt to also support this.

### PR DESCRIPTION
**Pull request by dazinator**
This is not yet ready to be merged, just opening whilst WIP.

- [x] extend options with a `fileSystem` param.
- [x] update [require js config](https://github.com/webforge-labs/requirejs-config-file) dependency to accept `fileSystem` option. PR https://github.com/webforge-labs/requirejs-config-file/pull/9 MERGED
- [ ] update [file-exists](https://github.com/scottcorgan/file-exists) dependency, to accept `fileSystem` option (waiting on PR https://github.com/scottcorgan/file-exists/pull/15) (submitted under seperate PR as this one was closed: #26)
- [ ] update [find](https://github.com/yuanchuan/find/) dependency, to accept `fileSystem` option. PR submitted: https://github.com/yuanchuan/find/pull/21 (submitted under seperate PR as this one was closed: https://github.com/dependents/node-module-lookup-amd/pull/26)

Closes #20

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
@dazinator wow. This is getting pretty involved no? You're a champ for pushing through the layers here.

**Comment by dazinator** [comment]
Yeah.. it is getting a little involved.. I'm still worried it might all be for nothing but we shall see, I haven;t heard anything from the `file-exists` author yet, I'll give it a few more weeks, but if there are dependencies that are no longer actively maintained, then that's the worry from my side as I wont be able to push things through.

**Comment by dazinator** [comment]
rebased on master.

**Comment by mrjoelkemp** [comment]
Looked good to merge. Released a new minor version with doc changes. Thanks for contributing @dazinator.

**Comment by dazinator** [comment]
No problem, thanks for merging. There are still a couple of dependencies to update to nake this work fully though i.e the two unchecked ticked boxes in the pr description. I'll submit another Pr for those changes (basically bumping dep versions) when they are ready ;-)

**Comment by dazinator** [comment]
Once a new build of 'find' dependency is available: https://travis-ci.org/yuanchuan/find/builds
I'll submit a PR that bumps to this dependency to the new version and uses the new API that allows alternative 'fs' to be passed.

I haven't heard anything regarding this PR yet: https://github.com/scottcorgan/file-exists/pull/15 so worst case scenario is that I'd have to create my own fork of `file-exists` if that repo has gone stale.

**Pull request merged**
